/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Fitness.Ejercicio;
import Fitness.Fecha;
import Fitness.InternalEjercicioException;
import Fitness.Maquina;
import Fitness.Medida;
import Fitness.ProgramaEntrenamiento;
import static GUI.MenuMedidas.MedicionTab;
import static GUI.MenuPaciente.pacientes;
import static GUI.MenuPaciente.posPaciente;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.swing.JOptionPane;

/**
 *
 * @author will
 */
public class MenuEjercicios extends javax.swing.JFrame {
    
    private static final NonEditableTableModel ejerciciosTableModel = new NonEditableTableModel();
    private static final String[] ejerciciosHeaders = {"Num Ejercicio","Descripción"};
    
    private ProgramaEntrenamiento programaEntrenamiento;
    private ArrayList<Ejercicio> ejerciciosActuales = new ArrayList<>();
    private Ejercicio ejercicioActual;
    

    /**
     * Creates new form MenuEjercicios
     */
    public MenuEjercicios() {
        initComponents();
        refreshCbxDescripcion();
    }
    
    public MenuEjercicios(ProgramaEntrenamiento pProgramaEntrenamiento) throws NullPointerException {
        if(pProgramaEntrenamiento == null)
        {
            throw new NullPointerException("no hay programa de entrenamiento seleccionado");
        }
        initComponents();
        
        programaEntrenamiento = pProgramaEntrenamiento;
        refreshCbxDescripcion();
        refreshTblEjercicios();
        refreshCbxDiaEjercicio();
        if(programaEntrenamiento.getDiasEjercicio().size() > 0)
        {
            ejerciciosActuales = programaEntrenamiento.getDiasEjercicio().get(0);
            
        }
    }
    
    public void refreshCbxDiaEjercicio()
    {
        System.out.println("dia");
        cbx_DiaEjercicio.removeAllItems();
        
        int canDiasEjercicio = programaEntrenamiento.getDiasEjercicio().size();
        for(int index = 0; index < canDiasEjercicio; index++)
        {
            String diaDesp = "Día " + Integer.toString(index + 1);
            cbx_DiaEjercicio.addItem((Object) diaDesp);
        }
        
        int index = cbx_DiaEjercicio.getSelectedIndex();
        ejerciciosActuales = programaEntrenamiento.getDiasEjercicio().get(index);
    }
    
    public void refreshCbxDescripcion()
    {
        cbx_Descripcion.removeAllItems();
        
        for(String desEjercicio : MenuConfigEjercicio.tipoEjercicios)
        {
            cbx_Descripcion.addItem((Object)desEjercicio);
        }
    }
    
    public void refreshTblEjercicios()
    {
        int listSize = ejerciciosActuales.size();
        String[][] ejerciciosDatos = new String[listSize][2];
        for(int index = 0; index < listSize; index++)
        {
            Ejercicio ejercicio = ejerciciosActuales.get(index);
            ejerciciosDatos[index][0]= ejercicio.getNumEjercicio();
            ejerciciosDatos[index][1] = ejercicio.getDescripcion();
        }
        
        ejerciciosTableModel.setDataVector(ejerciciosDatos, ejerciciosHeaders);
        tbl_Ejercicios.setModel(ejerciciosTableModel);
        
    }
    
    private boolean esFormularioValido()
    {
        boolean res = true;
        
        int numSeries = (Integer)spr_NumSeries.getValue();
        int numRepeticiones = (Integer)spr_NumRepeticiones.getValue();
        int tiempoDescanso = (Integer)spr_TiempoDescanso.getValue();
        
        res = (numSeries > 0) && (numRepeticiones > 0) && (tiempoDescanso > 0);
        
        return res;
    }
    
    private void cleanForm()
    {
        tf_NumEjercicio.setText("");
        cbx_Descripcion.setSelectedIndex(0);
        spr_NumSeries.repaint();
        spr_NumRepeticiones.repaint();
        spr_Peso1.repaint();
        spr_Peso2.repaint();
        spr_Peso3.repaint();
        spr_TiempoDescanso.repaint();
        ejercicioActual = null;
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cbx_DiaEjercicio = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_Ejercicios = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tf_NumEjercicio = new javax.swing.JTextField();
        spr_NumSeries = new javax.swing.JSpinner();
        spr_NumRepeticiones = new javax.swing.JSpinner();
        spr_TiempoDescanso = new javax.swing.JSpinner();
        spr_Peso1 = new javax.swing.JSpinner();
        spr_Peso3 = new javax.swing.JSpinner();
        spr_Peso2 = new javax.swing.JSpinner();
        cbx_Maquina = new javax.swing.JComboBox();
        cbx_Descripcion = new javax.swing.JComboBox();
        btn_Guardar = new javax.swing.JButton();
        btn_Cancelar = new javax.swing.JButton();
        btn_Borrar = new javax.swing.JButton();
        btn_AgregarDia = new javax.swing.JButton();
        btn_BorrarDia = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ejercicios");

        jLabel1.setLabelFor(cbx_DiaEjercicio);
        jLabel1.setText("Dia Ejercicio");

        cbx_DiaEjercicio.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbx_DiaEjercicio.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbx_DiaEjercicioItemStateChanged(evt);
            }
        });

        tbl_Ejercicios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_Ejercicios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_EjerciciosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_Ejercicios);

        jLabel2.setText("Num Ejercicio");

        jLabel3.setText("Descripción");

        jLabel4.setText("Num Series");

        jLabel5.setText("Num Repeticiones");

        jLabel6.setText("Peso1");

        jLabel7.setText("Tiempo Descanso");
        jLabel7.setToolTipText("");

        jLabel8.setText("Peso2");

        jLabel9.setText("Peso3");

        jLabel10.setText("Máquina");

        tf_NumEjercicio.setToolTipText("");

        spr_NumSeries.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));

        spr_NumRepeticiones.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));

        spr_TiempoDescanso.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));

        spr_Peso1.setModel(new javax.swing.SpinnerNumberModel(Double.valueOf(0.0d), Double.valueOf(0.0d), null, Double.valueOf(0.5d)));

        spr_Peso3.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));

        spr_Peso2.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));

        cbx_Maquina.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbx_Descripcion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btn_Guardar.setText("Guardar");
        btn_Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_GuardarActionPerformed(evt);
            }
        });

        btn_Cancelar.setText("Cancelar");
        btn_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CancelarActionPerformed(evt);
            }
        });

        btn_Borrar.setText("Borrar");
        btn_Borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BorrarActionPerformed(evt);
            }
        });

        btn_AgregarDia.setText("Agregar");
        btn_AgregarDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AgregarDiaActionPerformed(evt);
            }
        });

        btn_BorrarDia.setText("Borrar");
        btn_BorrarDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BorrarDiaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(cbx_DiaEjercicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_AgregarDia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_BorrarDia))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spr_NumRepeticiones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spr_TiempoDescanso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spr_NumSeries, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbx_Descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_NumEjercicio, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Guardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Borrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_Cancelar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9))
                                .addGap(48, 48, 48)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(spr_Peso1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(spr_Peso2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(spr_Peso3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbx_Maquina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbx_DiaEjercicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_AgregarDia)
                    .addComponent(btn_BorrarDia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(spr_Peso1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spr_Peso2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(spr_Peso3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cbx_Maquina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(jLabel8))
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_Guardar)
                            .addComponent(btn_Borrar)
                            .addComponent(btn_Cancelar))
                        .addGap(154, 154, 154))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tf_NumEjercicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cbx_Descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(spr_NumSeries, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(spr_NumRepeticiones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(spr_TiempoDescanso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CancelarActionPerformed
        this.dispose();
        
    }//GEN-LAST:event_btn_CancelarActionPerformed

    private void btn_GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_GuardarActionPerformed
        if(esFormularioValido())
        {
            String numEjercicio = tf_NumEjercicio.getText();
            String descripcion = (String)cbx_Descripcion.getSelectedItem();
            int numSeries = (Integer)spr_NumSeries.getValue();
            int numRepeticiones = (Integer)spr_NumRepeticiones.getValue();
            int tiempoDescanso = (Integer)spr_TiempoDescanso.getValue();
            double peso1 = (Double)spr_Peso1.getValue();
            double peso2 = (Double)spr_Peso2.getValue();
            double peso3 = (Double)spr_Peso3.getValue();

            int indexCbxMaquina = cbx_Maquina.getSelectedIndex();
            Maquina maquina = indexCbxMaquina > 0 ? (Maquina)cbx_Maquina.getSelectedItem() : null;

            try
            {

                ejercicioActual.setNumEjercicio(numEjercicio);
                ejercicioActual.setDescripcion(descripcion);
                ejercicioActual.setNumSeries(numSeries);
                ejercicioActual.setNumRepeticiones(numRepeticiones);
                ejercicioActual.setTiempoDescanso(tiempoDescanso);
                ejercicioActual.setPeso1(peso1);
                ejercicioActual.setPeso2(peso2);
                ejercicioActual.setPeso3(peso3);
                ejercicioActual.setMaquina(maquina);

            }
            catch(InternalEjercicioException ex)
            {
                JOptionPane.showMessageDialog(this, ex.getMessage());
                return;
            }
            catch(NullPointerException ex)
            {
                try
                {
                    

                    ejercicioActual = new Ejercicio();
                    ejercicioActual.setNumEjercicio(numEjercicio);
                    ejercicioActual.setDescripcion(descripcion);
                    ejercicioActual.setNumSeries(numSeries);
                    ejercicioActual.setNumRepeticiones(numRepeticiones);
                    ejercicioActual.setTiempoDescanso(tiempoDescanso);
                    ejercicioActual.setPeso1(peso1);
                    ejercicioActual.setPeso2(peso2);
                    ejercicioActual.setPeso3(peso3);
                    ejercicioActual.setMaquina(maquina);
                }
                catch(InternalEjercicioException e)
                {
                    JOptionPane.showMessageDialog(this, e.getMessage());
                    return;
                }
            }
            

            ejerciciosActuales.add(ejercicioActual);
            cleanForm();
            refreshTblEjercicios();
            JOptionPane.showMessageDialog(rootPane, peso3);
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Algunos datos del formulario no son válidos");
        }
        
    }//GEN-LAST:event_btn_GuardarActionPerformed

    private void btn_BorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BorrarActionPerformed
        ejerciciosActuales.remove(ejercicioActual);
        refreshTblEjercicios();
        cleanForm();
    }//GEN-LAST:event_btn_BorrarActionPerformed

    private void tbl_EjerciciosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_EjerciciosMouseClicked
        int indexRow = tbl_Ejercicios.getSelectedRow();
        
        String numEjercicio = (String)tbl_Ejercicios.getValueAt(indexRow, 0);
        
        for(Ejercicio ejercicio : ejerciciosActuales)
        {
            if(numEjercicio.equals(ejercicio.getNumEjercicio()))
            {
                ejercicioActual = ejercicio;
                return;
            }
        }
        
        tf_NumEjercicio.setText(ejercicioActual.getNumEjercicio());
        cbx_Descripcion.setSelectedItem((Object)ejercicioActual.getDescripcion());
        spr_NumSeries.setValue((Object)ejercicioActual.getNumSeries());
        spr_NumRepeticiones.setValue((Object)ejercicioActual.getNumRepeticiones());
        spr_TiempoDescanso.setValue((Object)ejercicioActual.getTiempoDescanso());
        spr_Peso1.setValue((Object)ejercicioActual.getPeso1());
        spr_Peso2.setValue((Object)ejercicioActual.getPeso2());
        spr_Peso3.setValue((Object)ejercicioActual.getPeso3());
        if(ejercicioActual.getMaquina() != null)
        {
            cbx_Maquina.setSelectedItem((Object)ejercicioActual.getMaquina());
        }
        
    }//GEN-LAST:event_tbl_EjerciciosMouseClicked

    private void cbx_DiaEjercicioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbx_DiaEjercicioItemStateChanged
        int index = cbx_DiaEjercicio.getSelectedIndex();
        ejerciciosActuales = programaEntrenamiento.getDiasEjercicio().get(index);
        refreshTblEjercicios();
    }//GEN-LAST:event_cbx_DiaEjercicioItemStateChanged

    private void btn_AgregarDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AgregarDiaActionPerformed
        
        int index = cbx_DiaEjercicio.getSelectedIndex();
        cbx_DiaEjercicio.removeItemAt(index);
        programaEntrenamiento.getDiasEjercicio().add(new ArrayList<>());
        refreshCbxDiaEjercicio();
        refreshTblEjercicios();
    }//GEN-LAST:event_btn_AgregarDiaActionPerformed

    private void btn_BorrarDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BorrarDiaActionPerformed
        int index = programaEntrenamiento.getDiasEjercicio().size();
        String dia = "Día " + Integer.toString(index);
        cbx_DiaEjercicio.addItem((Object)dia);
        
        programaEntrenamiento.getDiasEjercicio().remove(index);
        refreshCbxDiaEjercicio();
        refreshTblEjercicios();
    }//GEN-LAST:event_btn_BorrarDiaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuEjercicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuEjercicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuEjercicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuEjercicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuEjercicios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_AgregarDia;
    private javax.swing.JButton btn_Borrar;
    private javax.swing.JButton btn_BorrarDia;
    private javax.swing.JButton btn_Cancelar;
    private javax.swing.JButton btn_Guardar;
    private javax.swing.JComboBox cbx_Descripcion;
    private javax.swing.JComboBox cbx_DiaEjercicio;
    private javax.swing.JComboBox cbx_Maquina;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner spr_NumRepeticiones;
    private javax.swing.JSpinner spr_NumSeries;
    private javax.swing.JSpinner spr_Peso1;
    private javax.swing.JSpinner spr_Peso2;
    private javax.swing.JSpinner spr_Peso3;
    private javax.swing.JSpinner spr_TiempoDescanso;
    private javax.swing.JTable tbl_Ejercicios;
    private javax.swing.JTextField tf_NumEjercicio;
    // End of variables declaration//GEN-END:variables
}
