/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Fitness.Ejercicio;
import Fitness.Maquina;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author will
 * 
 */
public class MenuConfigEjercicio extends javax.swing.JFrame {

    
    
    public static final ArrayList<String> tipoEjercicios = new ArrayList<>();
    private int indexTipoEjercicioActual = -1;
    
    private final NonEditableTableModel ejercicioTableModel = new NonEditableTableModel();
    private final String[] ejercicioHeader = {"Num Ejercicio", "Descripción"};
    /**
     * Creates new form MenuConfigEjercicio
     */
    public MenuConfigEjercicio() {
        initComponents();
        refreshTblEjercicio();
    }
    
    public void clearForm()
    {
        tf_Descripcion.setText("");
        indexTipoEjercicioActual = -1;
    }
    
    private void refreshTblEjercicio()
    {
        String[][] ejercicioDatos = new String[tipoEjercicios.size()][2];
        
        for(int index = 0; index < tipoEjercicios.size(); index++)
        {
            ejercicioDatos[index][0] = Integer.toString(index+1);
            ejercicioDatos[index][1] = (String)tipoEjercicios.get(index);
        }
        
        ejercicioTableModel.setDataVector(ejercicioDatos, ejercicioHeader);
        
        tbl_Ejercicio.setModel(ejercicioTableModel);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_Ejercicio = new javax.swing.JTable();
        tf_Descripcion = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btn_Guardar = new javax.swing.JButton();
        btn_Borrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbl_Ejercicio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_Ejercicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_EjercicioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_Ejercicio);

        tf_Descripcion.setToolTipText("Descripcion");

        jLabel1.setText("Descripción");

        btn_Guardar.setText("Guardar");
        btn_Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_GuardarActionPerformed(evt);
            }
        });

        btn_Borrar.setText("Borrar");
        btn_Borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BorrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_Descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                        .addComponent(btn_Guardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_Borrar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Guardar)
                    .addComponent(btn_Borrar)
                    .addComponent(jLabel1)
                    .addComponent(tf_Descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_GuardarActionPerformed
        
        String descripcion = tf_Descripcion.getText();
        
        if(!descripcion.isEmpty())
        {
            if(indexTipoEjercicioActual > -1)
            {
                tipoEjercicios.set(indexTipoEjercicioActual, descripcion);
            }
            else
            {
                tipoEjercicios.add(descripcion);
            }
        }
        refreshTblEjercicio();
        
        
    }//GEN-LAST:event_btn_GuardarActionPerformed

    private void btn_BorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BorrarActionPerformed
        if(indexTipoEjercicioActual > -1)
        {
            tipoEjercicios.remove(indexTipoEjercicioActual);
        }
        clearForm();
        refreshTblEjercicio();
    }//GEN-LAST:event_btn_BorrarActionPerformed

    private void tbl_EjercicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_EjercicioMouseClicked
        int indexRow = tbl_Ejercicio.getSelectedRow();
        Object objetoNumEjercicio = tbl_Ejercicio.getValueAt(indexRow, 0);
        indexTipoEjercicioActual = Integer.parseInt(objetoNumEjercicio.toString()) + 1;
        String textoDescripcion = (String)tbl_Ejercicio.getValueAt(indexRow, 1);
        tf_Descripcion.setText(textoDescripcion);
        
    }//GEN-LAST:event_tbl_EjercicioMouseClicked

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuConfigEjercicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuConfigEjercicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuConfigEjercicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuConfigEjercicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuConfigEjercicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Borrar;
    private javax.swing.JButton btn_Guardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_Ejercicio;
    private javax.swing.JTextField tf_Descripcion;
    // End of variables declaration//GEN-END:variables
}
