/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Fitness.Fecha;
import Fitness.Medida;
import Fitness.Paciente;

import static GUI.MenuPaciente.pacientes;
import static GUI.MenuPaciente.posPaciente;
import static GUI.MenuPaciente.gener;
import static GUI.MenuPaciente.eda;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.List;

import javax.swing.JOptionPane;
import javax.swing.JTable;



/**
 *
 * @author admin
 */
public class MenuMedidas extends javax.swing.JFrame {
    
    /**
     * Creates new form MenuMedidas
     */
    public static int numeroMedida;
    private static final NonEditableTableModel medidaTableModel = new NonEditableTableModel();
    private static final String[] medidaHeaders = {"Medidas","Fecha"};
    public MenuMedidas() {       
        initComponents();
        refreshMedidaTab();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Estatura = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Peso = new javax.swing.JTextField();
        Subescapular = new javax.swing.JTextField();
        Triceps = new javax.swing.JTextField();
        Abdomen = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Iliaco = new javax.swing.JTextField();
        Pantorrilla = new javax.swing.JTextField();
        Muslo = new javax.swing.JTextField();
        Cuello = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        Pectoral = new javax.swing.JTextField();
        BicepIzq = new javax.swing.JTextField();
        BicepDer = new javax.swing.JTextField();
        PectoralCircum = new javax.swing.JTextField();
        Espalda = new javax.swing.JTextField();
        Cintura1 = new javax.swing.JTextField();
        Cintura2 = new javax.swing.JTextField();
        Cintura3 = new javax.swing.JTextField();
        Cadera = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        MusloDer = new javax.swing.JTextField();
        MusloIzq = new javax.swing.JTextField();
        PantorrillaDer = new javax.swing.JTextField();
        PantorrillaIzq = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        PresionArtSist = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        FrecuenciaReposo = new javax.swing.JTextField();
        PresionArtDiast = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        agregar = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        calcular = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        MedicionTab = new javax.swing.JTable();
        porcentajeGrasaCorp = new javax.swing.JLabel();
        MasaMusc = new javax.swing.JLabel();
        CintCad = new javax.swing.JLabel();
        FreqCard = new javax.swing.JLabel();
        Guardar = new javax.swing.JButton();

        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Medidas del paciente");

        Estatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EstaturaActionPerformed(evt);
            }
        });

        jLabel2.setText("Estatura");

        jLabel3.setText("Peso");

        jLabel4.setText("Triceps");

        jLabel5.setText("--- Pliegues cutaneos(mm) ---");

        jLabel6.setText("Subescapular");

        jLabel7.setText("Abdomen");

        jLabel8.setText("Iliaco");

        jLabel9.setText("Muslo");

        jLabel10.setText("Pantorrilla");

        jLabel11.setText("Pectoral");

        jLabel12.setText("-------------- Circumferencias corporal(centimetros)---------------");

        jLabel13.setText("Cuello");

        jLabel14.setText("Bicep derecho");

        jLabel15.setText("Bicep Izquierdo");

        jLabel16.setText("Pectoral");

        jLabel17.setText("Espalda");

        jLabel18.setText("Cintura 1");

        jLabel19.setText("Cintura 2");

        jLabel20.setText("Cintura 3");

        jLabel21.setText("Cadera");

        jLabel22.setText("Muslo derecho");

        jLabel23.setText("Muslo izquierdo");

        jLabel24.setText("Pantorrilla derecha");

        jLabel25.setText("Pantorrilla izquierda");

        jLabel26.setText("Ferecuencia en reposo");

        jLabel27.setText("-- Presion Arterial(milimetros de mercurio) --");

        jLabel28.setText("Sistolica");

        jLabel29.setText("Diastolica");

        jLabel30.setText("-----------------------------------------------");

        jLabel31.setText("(metros)");

        jLabel32.setText("(kg)");

        jLabel33.setText("latidos");

        jLabel34.setText("por minuto");

        agregar.setText("Agregar");
        agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActionPerformed(evt);
            }
        });

        cancelar.setText("Salir");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        jLabel36.setText("Porcentaje Grasa Corporar");

        jLabel37.setText("Porcentaje Masa Muscular");

        jLabel38.setText("Relacion cintura/cadera");

        jLabel39.setText("Frecuencia Cardiaca");

        calcular.setText("Calcular");
        calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularActionPerformed(evt);
            }
        });

        MedicionTab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Medicion", "Fecha"
            }
        ));
        MedicionTab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MedicionTabMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(MedicionTab);

        porcentajeGrasaCorp.setText("0%");

        MasaMusc.setText("0%");

        CintCad.setText("0");

        FreqCard.setText("0/min");

        Guardar.setText("Guardar");
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(666, 666, 666)
                                .addComponent(Guardar)
                                .addGap(32, 32, 32)
                                .addComponent(agregar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cancelar))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel11))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(Estatura)
                                            .addComponent(Peso)
                                            .addComponent(Subescapular)
                                            .addComponent(Triceps)
                                            .addComponent(Abdomen)
                                            .addComponent(Iliaco)
                                            .addComponent(Pantorrilla)
                                            .addComponent(Muslo)
                                            .addComponent(Pectoral, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel31)
                                            .addComponent(jLabel32)))
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel13)
                                            .addComponent(jLabel14))
                                        .addGap(31, 31, 31)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(Cuello)
                                            .addComponent(BicepDer, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel22)
                                            .addComponent(jLabel23)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel15)
                                            .addComponent(jLabel16)
                                            .addComponent(jLabel17)
                                            .addComponent(jLabel18)
                                            .addComponent(jLabel19)
                                            .addComponent(jLabel20)
                                            .addComponent(jLabel21))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(MusloIzq, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(BicepIzq, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(jLabel24)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(PantorrillaDer, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(PectoralCircum, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(jLabel25)
                                                        .addGap(32, 32, 32)
                                                        .addComponent(PantorrillaIzq, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addComponent(MusloDer, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(Espalda, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel30))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(Cadera, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(Cintura3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(Cintura2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(Cintura1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jLabel27)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                            .addComponent(FrecuenciaReposo, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                    .addComponent(jLabel26)
                                                                    .addComponent(jLabel28)
                                                                    .addComponent(jLabel29))
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                    .addGroup(layout.createSequentialGroup()
                                                                        .addGap(32, 32, 32)
                                                                        .addComponent(PresionArtSist, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                        .addComponent(PresionArtDiast, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jLabel33)
                                                            .addComponent(jLabel34)))))))
                                    .addComponent(jLabel12))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel36)
                                    .addComponent(jLabel39)
                                    .addComponent(calcular)
                                    .addComponent(jLabel37)
                                    .addComponent(jLabel38)
                                    .addComponent(porcentajeGrasaCorp)
                                    .addComponent(MasaMusc)
                                    .addComponent(CintCad)
                                    .addComponent(FreqCard))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                        .addComponent(jLabel35)
                        .addContainerGap(21, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel12)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(Estatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel2)
                                                    .addComponent(jLabel31))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(jLabel3)
                                                    .addComponent(Peso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel32))
                                                .addGap(14, 14, 14)
                                                .addComponent(jLabel5)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(Triceps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel4))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(Subescapular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel6))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(Abdomen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel7))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(Iliaco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel8))
                                                .addGap(12, 12, 12)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(Muslo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel9))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(Pantorrilla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel10))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(jLabel11)
                                                    .addComponent(Pectoral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(jLabel13)
                                                    .addComponent(Cuello, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel22)
                                                    .addComponent(MusloDer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(11, 11, 11)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(jLabel14)
                                                    .addComponent(BicepDer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel23)
                                                    .addComponent(MusloIzq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(41, 41, 41)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(jLabel15)
                                                    .addComponent(BicepIzq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel24)
                                                    .addComponent(PantorrillaDer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(PantorrillaIzq, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel16)
                                                        .addComponent(PectoralCircum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel25)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(jLabel17)
                                                    .addComponent(Espalda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel30))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(jLabel18)
                                                    .addComponent(Cintura1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel26)
                                                    .addComponent(jLabel33)
                                                    .addComponent(FrecuenciaReposo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(2, 2, 2)
                                                        .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(jLabel27))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                            .addComponent(Cintura2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(jLabel19))))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(jLabel20)
                                                    .addComponent(Cintura3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel28)
                                                    .addComponent(PresionArtSist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel21)
                                                        .addComponent(Cadera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel29)
                                                        .addComponent(PresionArtDiast, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                        .addGap(34, 34, 34))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel36)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(porcentajeGrasaCorp)
                                        .addGap(8, 8, 8)
                                        .addComponent(jLabel37)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(MasaMusc, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(4, 4, 4)
                                        .addComponent(jLabel38)
                                        .addGap(11, 11, 11)
                                        .addComponent(CintCad)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel39)
                                        .addGap(7, 7, 7)
                                        .addComponent(FreqCard)
                                        .addGap(18, 18, 18)
                                        .addComponent(calcular)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cancelar)
                                    .addComponent(agregar)
                                    .addComponent(Guardar)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(239, 239, 239)
                        .addComponent(jLabel35)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void refreshMedidaTab()
    {
        
        List<Medida> tempMediciones = pacientes.get(posPaciente).getMedida();
        String[][] medidaDatos = new String[tempMediciones.size()][2];
        for(int index = 0; index < tempMediciones.size(); index++)
        {
            Medida medida = tempMediciones.get(index);
            medidaDatos[index][0]= Integer.toString(index+1);
            medidaDatos[index][1] = medida.getFechaMedida().toString();
        }
        
        medidaTableModel.setDataVector(medidaDatos, medidaHeaders);
        MedicionTab.setModel(medidaTableModel);
        
    }
    
    
    private void EstaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EstaturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EstaturaActionPerformed

    
    
    
    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed
        
        try{
            if (Double.parseDouble(Estatura.getText())<=0||
            Double.parseDouble(Peso.getText())<=0||
            Double.parseDouble(Triceps.getText())<=0||
            Double.parseDouble(Subescapular.getText())<=0||
            Double.parseDouble(Abdomen.getText())<=0||
            Double.parseDouble(Iliaco.getText())<=0||
            Double.parseDouble(Muslo.getText())<=0||
            Double.parseDouble(Pantorrilla.getText())<=0||
            Double.parseDouble(Pectoral.getText())<=0||
            Double.parseDouble(Cuello.getText())<=0||
            Double.parseDouble(BicepDer.getText())<=0||
            Double.parseDouble(BicepIzq.getText())<=0||
            Double.parseDouble(PectoralCircum.getText())<=0||
            Double.parseDouble(Espalda.getText())<=0||
            Double.parseDouble(Cintura1.getText())<=0||
            Double.parseDouble(Cintura2.getText())<=0||
            Double.parseDouble(Cintura3.getText())<=0||
            Double.parseDouble(Cadera.getText())<=0||
            Double.parseDouble(MusloDer.getText())<=0||
            Double.parseDouble(MusloIzq.getText())<=0||
            Double.parseDouble(PantorrillaDer.getText())<=0||
            Double.parseDouble(PantorrillaIzq.getText())<=0||
            Integer.valueOf(FrecuenciaReposo.getText())<=0||
            Double.parseDouble(PresionArtSist.getText())<=0||
            Double.parseDouble(PresionArtDiast.getText())<=0){
                JOptionPane.showMessageDialog(this, "No debe haber cantidades negativas");
            return;
            }
            
            
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Una o mas de las opciones no son validas, por favor revisar");
            return;
        }
        Medida medicion = new Medida();
         
        medicion.setEstatura(Double.parseDouble(Estatura.getText()));
        medicion.setPeso(Double.parseDouble(Peso.getText()));
        medicion.setTriceps(Double.parseDouble(Triceps.getText()));
        medicion.setSubescapular(Double.parseDouble(Subescapular.getText()));
        medicion.setAbdomen(Double.parseDouble(Abdomen.getText()));
        medicion.setIliaco(Double.parseDouble(Iliaco.getText()));
        medicion.setMuslo(Double.parseDouble(Muslo.getText()));
        medicion.setPantorrilla(Double.parseDouble(Pantorrilla.getText()));
        medicion.setPectoral(Double.parseDouble(Pectoral.getText()));
        medicion.setCuello(Double.parseDouble(Cuello.getText()));
        medicion.setBicepDer(Double.parseDouble(BicepDer.getText()));
        medicion.setBicepIzq(Double.parseDouble(BicepIzq.getText()));
        medicion.setPectoralCircum(Double.parseDouble(PectoralCircum.getText()));
        medicion.setEspalda(Double.parseDouble(Espalda.getText()));
        medicion.setCintura1(Double.parseDouble(Cintura1.getText()));
        medicion.setCintura2(Double.parseDouble(Cintura2.getText()));
        medicion.setCintura3(Double.parseDouble(Cintura3.getText()));
        medicion.setCadera(Double.parseDouble(Cadera.getText()));
        medicion.setMusloDerecho(Double.parseDouble(MusloDer.getText()));
        medicion.setMusloIzquierdo(Double.parseDouble(MusloIzq.getText()));
        medicion.setPantorrillaDerecha(Double.parseDouble(PantorrillaDer.getText()));
        medicion.setPantorrillaIzquierda(Double.parseDouble(PantorrillaIzq.getText()));
        medicion.setFrecuenciaCardiacaReposo(Integer.valueOf(FrecuenciaReposo.getText()));
        medicion.setPresionArterialSistolica(Double.parseDouble(PresionArtSist.getText()));
        medicion.setPresionArterialDiastolica(Double.parseDouble(PresionArtDiast.getText()));
        Fecha fechaCreado = new Fecha(LocalDate.now());
        medicion.setFechaMedida(fechaCreado);
        pacientes.get(posPaciente).agregarMedida(medicion);
        
        refreshMedidaTab();
    }//GEN-LAST:event_agregarActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed

        setVisible(false);
    }//GEN-LAST:event_cancelarActionPerformed

    private void calcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularActionPerformed
        try{
            if(Double.parseDouble(Estatura.getText())<=0||
            Double.parseDouble(Peso.getText())<=0||
            Double.parseDouble(Cintura1.getText())<=0||
            Double.parseDouble(Cintura2.getText())<=0||
            Double.parseDouble(Cintura3.getText())<=0||
            Double.parseDouble(Cadera.getText())<=0){
                JOptionPane.showMessageDialog(this, "No debe haber cantidades negativas");
            return;
            }
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Una o mas de las opciones no son validas, por favor revisar");
            return;
        }
        Medida medicion2 = new Medida();
        medicion2.setEstatura(Double.parseDouble(Estatura.getText()));
        medicion2.setPeso(Double.parseDouble(Peso.getText()));
        medicion2.setCintura1(Double.parseDouble(Cintura1.getText()));
        medicion2.setCintura2(Double.parseDouble(Cintura2.getText()));
        medicion2.setCintura3(Double.parseDouble(Cintura3.getText()));
        medicion2.setCadera(Double.parseDouble(Cadera.getText()));
        
        double porcGrasaCorp=medicion2.calcPorcentajeGrasaCorporal(eda,gener);
        String porcGrasaCorpString = String.format("%.2f", porcGrasaCorp);
        porcentajeGrasaCorp.setText(porcGrasaCorpString+"%");  
        
        double porcMasaMusc=medicion2.calcPorcentajeMasaMuscular();
        String porcMasaMuscString=String.format("%.2f", porcMasaMusc);
        MasaMusc.setText(porcMasaMuscString+"%");
        
        double cintura_cadera=medicion2.calcRelacionCinturaCadera();
        String porcCintura_caderaString=String.format("%.5f",cintura_cadera);
        CintCad.setText(porcCintura_caderaString);
        
        int frequenciaCard=medicion2.calcFrecuenciaCard(eda);
        FreqCard.setText(Integer.toString(frequenciaCard)+"/min");
    }//GEN-LAST:event_calcularActionPerformed

    private void MedicionTabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MedicionTabMouseClicked
        JTable MedTab = (JTable)evt.getSource();
        //int indexCol = miTabla.getSelectedColumn();
        int indexRow = MedTab.getSelectedRow();
        //String elemento = (String)miTabla.getValueAt(indexRow, indexCol);
        numeroMedida=indexRow;
        Medida tempMedida = pacientes.get(posPaciente).getMedida().get(indexRow);
        Estatura.setText(Double.toString(tempMedida.getEstatura()));
        Peso.setText(Double.toString(tempMedida.getPeso()));
        Triceps.setText(Double.toString(tempMedida.getTriceps()));
        Subescapular.setText(Double.toString(tempMedida.getSubescapular()));
        Abdomen.setText(Double.toString(tempMedida.getAbdomen()));
        Iliaco.setText(Double.toString(tempMedida.getIliaco()));
        Muslo.setText(Double.toString(tempMedida.getMuslo()));
        Pantorrilla.setText(Double.toString(tempMedida.getPantorrilla()));
        Pectoral.setText(Double.toString(tempMedida.getPectoral()));
        Cuello.setText(Double.toString(tempMedida.getCuello()));
        BicepDer.setText(Double.toString(tempMedida.getBicepDer()));
        BicepIzq.setText(Double.toString(tempMedida.getBicepIzq()));
        PectoralCircum.setText(Double.toString(tempMedida.getPectoralCircum()));
        Espalda.setText(Double.toString(tempMedida.getEspalda()));
        Cintura1.setText(Double.toString(tempMedida.getCintura1()));
        Cintura2.setText(Double.toString(tempMedida.getCintura2()));
        Cintura3.setText(Double.toString(tempMedida.getCintura3()));
        Cadera.setText(Double.toString(tempMedida.getCadera()));
        MusloDer.setText(Double.toString(tempMedida.getMusloDerecho()));
        MusloIzq.setText(Double.toString(tempMedida.getMusloIzquierdo()));
        PantorrillaDer.setText(Double.toString(tempMedida.getPantorrillaDerecha()));
        PantorrillaIzq.setText(Double.toString(tempMedida.getPantorrillaIzquierda()));
        FrecuenciaReposo.setText(Integer.toString(tempMedida.getFrecuenciaCardiacaReposo()));
        PresionArtSist.setText(Double.toString(tempMedida.getPresionArterialSistolica()));
        PresionArtDiast.setText(Double.toString(tempMedida.getPresionArterialDiastolica()));
    }//GEN-LAST:event_MedicionTabMouseClicked

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        refreshMedidaTab();
    }//GEN-LAST:event_formFocusGained

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
        Medida tempMedida = pacientes.get(posPaciente).getMedida().get(numeroMedida);
        tempMedida.setEstatura(Double.parseDouble(Estatura.getText()));
        tempMedida.setPeso(Double.parseDouble(Peso.getText()));
        tempMedida.setTriceps(Double.parseDouble(Triceps.getText()));
        tempMedida.setSubescapular(Double.parseDouble(Subescapular.getText()));
        tempMedida.setAbdomen(Double.parseDouble(Abdomen.getText()));
        tempMedida.setIliaco(Double.parseDouble(Iliaco.getText()));
        tempMedida.setMuslo(Double.parseDouble(Muslo.getText()));
        tempMedida.setPantorrilla(Double.parseDouble(Pantorrilla.getText()));
        tempMedida.setPectoral(Double.parseDouble(Pectoral.getText()));
        tempMedida.setCuello(Double.parseDouble(Cuello.getText()));
        tempMedida.setBicepDer(Double.parseDouble(BicepDer.getText()));
        tempMedida.setBicepIzq(Double.parseDouble(BicepIzq.getText()));
        tempMedida.setPectoralCircum(Double.parseDouble(PectoralCircum.getText()));
        tempMedida.setEspalda(Double.parseDouble(Espalda.getText()));
        tempMedida.setCintura1(Double.parseDouble(Cintura1.getText()));
        tempMedida.setCintura2(Double.parseDouble(Cintura2.getText()));
        tempMedida.setCintura3(Double.parseDouble(Cintura3.getText()));
        tempMedida.setCadera(Double.parseDouble(Cadera.getText()));
        tempMedida.setMusloDerecho(Double.parseDouble(MusloDer.getText()));
        tempMedida.setMusloIzquierdo(Double.parseDouble(MusloIzq.getText()));
        tempMedida.setPantorrillaDerecha(Double.parseDouble(PantorrillaDer.getText()));
        tempMedida.setPantorrillaIzquierda(Double.parseDouble(PantorrillaIzq.getText()));
        tempMedida.setFrecuenciaCardiacaReposo(Integer.valueOf(FrecuenciaReposo.getText()));
        tempMedida.setPresionArterialSistolica(Double.parseDouble(PresionArtSist.getText()));
        tempMedida.setPresionArterialDiastolica(Double.parseDouble(PresionArtDiast.getText()));
        refreshMedidaTab();
    }//GEN-LAST:event_GuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuMedidas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuMedidas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuMedidas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuMedidas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuMedidas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField Abdomen;
    public static javax.swing.JTextField BicepDer;
    public static javax.swing.JTextField BicepIzq;
    public static javax.swing.JTextField Cadera;
    public static javax.swing.JLabel CintCad;
    public static javax.swing.JTextField Cintura1;
    public static javax.swing.JTextField Cintura2;
    public static javax.swing.JTextField Cintura3;
    public static javax.swing.JTextField Cuello;
    public static javax.swing.JTextField Espalda;
    public static javax.swing.JTextField Estatura;
    public static javax.swing.JTextField FrecuenciaReposo;
    public static javax.swing.JLabel FreqCard;
    private javax.swing.JButton Guardar;
    public static javax.swing.JTextField Iliaco;
    public static javax.swing.JLabel MasaMusc;
    public static javax.swing.JTable MedicionTab;
    public static javax.swing.JTextField Muslo;
    public static javax.swing.JTextField MusloDer;
    public static javax.swing.JTextField MusloIzq;
    public static javax.swing.JTextField Pantorrilla;
    public static javax.swing.JTextField PantorrillaDer;
    public static javax.swing.JTextField PantorrillaIzq;
    public static javax.swing.JTextField Pectoral;
    public static javax.swing.JTextField PectoralCircum;
    public static javax.swing.JTextField Peso;
    public static javax.swing.JTextField PresionArtDiast;
    public static javax.swing.JTextField PresionArtSist;
    public static javax.swing.JTextField Subescapular;
    public static javax.swing.JTextField Triceps;
    private javax.swing.JButton agregar;
    private javax.swing.JButton calcular;
    private javax.swing.JButton cancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JLabel porcentajeGrasaCorp;
    // End of variables declaration//GEN-END:variables

    

    
}
