/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Fitness.Ejercicio;
import Fitness.Maquina;
import Fitness.Paciente;
import Fitness.ProgramaEntrenamiento;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author will
 * 
 */
public class MenuConfigEjercicio extends javax.swing.JFrame {

    
    
    public static final ArrayList<String> tipoEjercicios = new ArrayList<>();
    private int indexTipoEjercicioActual = -1;
    
    private final NonEditableTableModel ejercicioTableModel = new NonEditableTableModel();
    private final String[] ejercicioHeader = {"Num Ejercicio", "Descripción"};
    /**
     * Creates new form MenuConfigEjercicio
     */
    public MenuConfigEjercicio() {
        initComponents();
        refreshTblEjercicio();
    }
    
    public void clearForm()
    {
        tf_Descripcion.setText("");
        indexTipoEjercicioActual = -1;
    }
    
    private void refreshTblEjercicio()
    {
        String[][] ejercicioDatos = new String[tipoEjercicios.size()][2];
        
        for(int index = 0; index < tipoEjercicios.size(); index++)
        {
            ejercicioDatos[index][0] = Integer.toString(index+1);
            ejercicioDatos[index][1] = (String)tipoEjercicios.get(index);
        }
        
        ejercicioTableModel.setDataVector(ejercicioDatos, ejercicioHeader);
        
        tbl_Ejercicio.setModel(ejercicioTableModel);
    }
    
    private void removeEjerciciosFromEverywhere(String pEjercicioDes)
    {
        for(int indexPaciente = 0; indexPaciente < MenuPaciente.pacientes.size(); indexPaciente++)
        {
            Paciente paciente = MenuPaciente.pacientes.get(indexPaciente);
            int sizeProEntrenamiento = paciente.getProgramaEntrenamientoList().size();
            for(int indexProEntrenamiento = 0; indexProEntrenamiento < sizeProEntrenamiento; indexProEntrenamiento++)
            {
                ProgramaEntrenamiento proEntrenamiento = 
                        paciente.getProgramaEntrenamientoList().get(indexProEntrenamiento);
                
                for(int indexDia = 0; indexDia < proEntrenamiento.getDiasEjercicio().size(); indexDia++)
                {
                    ArrayList<Ejercicio> dia = proEntrenamiento.getDiasEjercicio().get(indexDia);
                    for(int indexEjercicio = 0; indexEjercicio < dia.size(); indexEjercicio++)
                    {
                        Ejercicio ejercicio = dia.get(indexEjercicio);
                        
                        if(pEjercicioDes.equals(ejercicio.getDescripcion()))
                        {
                            dia.remove(indexDia);
                        }
                    }
                }
            }
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_Ejercicio = new javax.swing.JTable();
        tf_Descripcion = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btn_Guardar = new javax.swing.JButton();
        btn_Borrar = new javax.swing.JButton();
        btn_Salir = new javax.swing.JButton();

        setTitle("Configuración Ejercicios");

        tbl_Ejercicio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_Ejercicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_EjercicioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_Ejercicio);

        tf_Descripcion.setToolTipText("Descripcion");

        jLabel1.setText("Descripción");

        btn_Guardar.setText("Guardar");
        btn_Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_GuardarActionPerformed(evt);
            }
        });

        btn_Borrar.setText("Borrar");
        btn_Borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BorrarActionPerformed(evt);
            }
        });

        btn_Salir.setText("Salir");
        btn_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(6, 6, 6)
                        .addComponent(tf_Descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_Guardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Borrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_Salir)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Guardar)
                    .addComponent(btn_Borrar)
                    .addComponent(jLabel1)
                    .addComponent(btn_Salir)
                    .addComponent(tf_Descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_GuardarActionPerformed
        
        String descripcion = tf_Descripcion.getText();
        
        if(!descripcion.isEmpty())
        {
            if(indexTipoEjercicioActual > -1)
            {
                tipoEjercicios.set(indexTipoEjercicioActual, descripcion);
            }
            else
            {
                tipoEjercicios.add(descripcion);
            }
        }
        refreshTblEjercicio();
        
        
    }//GEN-LAST:event_btn_GuardarActionPerformed

    private void btn_BorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BorrarActionPerformed
        int res = JOptionPane.showConfirmDialog(this, "El ejercicio que desea borrar puede estar enlazada con programas de entrenamiento, ¿Desea borrar la ejercicio?");
        if(res == 0)
        {
            if(indexTipoEjercicioActual > -1)
            {
                String ejercicioBorrar = tipoEjercicios.get(indexTipoEjercicioActual);
                removeEjerciciosFromEverywhere(ejercicioBorrar);
                tipoEjercicios.remove(indexTipoEjercicioActual);
            }

            clearForm();
            
        }
        refreshTblEjercicio();
    }//GEN-LAST:event_btn_BorrarActionPerformed

    private void tbl_EjercicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_EjercicioMouseClicked
        int indexRow = tbl_Ejercicio.getSelectedRow();
        Object objetoNumEjercicio = tbl_Ejercicio.getValueAt(indexRow, 0);
        indexTipoEjercicioActual = Integer.parseInt(objetoNumEjercicio.toString()) + 1;
        String textoDescripcion = (String)tbl_Ejercicio.getValueAt(indexRow, 1);
        tf_Descripcion.setText(textoDescripcion);
        
    }//GEN-LAST:event_tbl_EjercicioMouseClicked

    private void btn_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SalirActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btn_SalirActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuConfigEjercicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuConfigEjercicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuConfigEjercicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuConfigEjercicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuConfigEjercicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Borrar;
    private javax.swing.JButton btn_Guardar;
    private javax.swing.JButton btn_Salir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_Ejercicio;
    private javax.swing.JTextField tf_Descripcion;
    // End of variables declaration//GEN-END:variables
}
